# Manipulating data

This chapter provides an introduction to manipulating datasets using the **dplyr** package.
**dplyr** is part of the **tidyverse**, which aims to provide a user friendly framework for data science.
It is not everyone's cup of tea but experience of teaching R over the past few years suggests that people find it easier to get going with data driven research if they learn the 'tidy' workflow presented in this chapter.
The aim is not to impose this style and if you do not like this style of R code, or if you are simply curious, we encourage you to try alternative approaches for achieving the same results using base R [@rcoreteam_language_2020]^[
Run the command `help.start()` to see a resources introducing base R, and [Chapter 6 on lists and data frames](https://cran.r-project.org/doc/manuals/r-release/R-intro.html#Lists-and-data-frames) in [An Introduction to R](https://cran.r-project.org/doc/manuals/r-release/R-intro.pdf) in particular for an introduction to data manipulation with base R.
] or `data.table` [@R-data.table] approaches in R or even in other languages such as [Python](https://www.python.org/) or [Julia](https://julialang.org/).
If you just want to get going with processing data we suggest learning how to manipulate data in R first.


