---
title: "Reproducible road safety research with R: A practical introduction"
author: "Robin Lovelace"
site: bookdown::bookdown_site
documentclass: book
output:
  bookdown::gitbook: default
  #bookdown::pdf_book: default
description: "A reproducible and open source approach to aapplied road safety research"
url: 'https\://saferactive.github.io/rrsrr/'
github-repo: "saferactive/rrsrr"
bibliography:
  - packages.bib
  - references.bib
---


```{r, include=FALSE, eval=FALSE}
citr::tidy_bib_file(rmd_file = "_main.Rmd", messy_bibliography = "~/uaf/allrefs.bib", file = "references.bib")
```


<!-- Structure outline -->

<!-- Preface -->

<!-- 1 Introduction -->
<!-- 2 R basics -->
<!-- 3 Using RStudio -->
<!-- 4 R Packages -->
<!-- 5 Manipulating data -->
<!-- 6 Temporal data -->
<!-- 7 Spatial data -->
<!-- 8 Joining road crash tables -->
<!-- 9 Next steps for reproducible road safety research -->

<!-- Structure full -->

<!-- Preface -->

<!-- 1 Introduction -->
<!-- 1.1 Why R for road safety research? . . . . . . . . . . . . . . . . . . -->
<!-- 1.2 Prerequisites . . . . . . . . . . . . . . . . . . . . . . . . . . . . . -->

<!-- 2 R basics -->
<!-- 2.1 Subsetting by index or name . -->
<!-- 2.2 Subsetting by values . . . . . . -->
<!-- 2.3 Dealing with NAs and recoding -->
<!-- 2.4 Changing class . . . . . . . . . -->
<!-- 2.5 Recoding values . . . . . . . . . -->
<!-- 2.6 Now you are ready to use R . . -->

<!-- 3 Using RStudio -->
<!-- 3.1 Projects and scripts . . . -->
<!-- 3.2 Writing and running code -->
<!-- 3.3 Viewing Objects . . . . . -->
<!-- 3.4 Autocompletion . . . . . . -->
<!-- 3.5 Getting help . . . . . . . . -->
<!-- 3.6 Commenting Code . . . . -->
<!-- 3.7 The global environment . -->
<!-- 3.8 Debugging Code . . . . . -->
<!-- 3.9 Saving R objects . . . . . -->

<!-- 4 R Packages -->
<!-- 4.1 What are packages? . . . . . . . . . . . . . . . . . . . . . . . . . 19 -->
<!-- 4.2 ggplot2 . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 20 -->
<!-- 4.3 dplyr and pipes . . . . . . . . . . . . . . . . . . . . . . . . . . . . 21 -->

<!-- 5 Manipulating data -->

<!-- 6 Temporal data -->

<!-- 7 Spatial data -->
<!-- 7.1 sf objects . . . . . . . . . . . . . . . . -->
<!-- 7.2 Reading and writing spatial data . . . -->
<!-- 7.3 sf polygons . . . . . . . . . . . . . . . -->
<!-- 7.4 Spatial subsetting and sf plotting . . . -->
<!-- 7.5 Geographic joins . . . . . . . . . . . . -->
<!-- 7.6 CRSs . . . . . . . . . . . . . . . . . . . -->
<!-- 7.7 Buffers . . . . . . . . . . . . . . . . . . -->
<!-- 7.8 Attribute operations on sf objects . . . -->
<!-- 7.9 Matching roads to crashes . . . . . . . -->
<!-- 7.10 Mapping road crash data . . . . . . . -->
<!-- 7.11 Analysing point data . . . . . . . . . . -->
<!-- 7.12 Analysing crash data on road networks -->

<!-- 8 Joining road crash tables -->

<!-- 9 Next steps for reproducible road safety research -->


# Preface {-}

Many areas of research have real world implications, but few have the ability to *save lives* in the way that road safety research does.
Road safety research is a data driven field of research, underpinned by attribute-rich spatio-temporal event-based datasets representing the grim reality of people who are tragically hurt or killed on the roads.
Because of the incessant nature of road casualties there is a danger that it becomes normalised, an implicitly accepted cost associated with the benefits of personal mobility.

Data analysis in general and 'data science' in particular has great potential to support more evidence-based road safety policies.
Data science can be defined as a particular type of data analysis process that is script-based, reproducible and scalable.
As such, it has the ability to represent what we know about road casualties in new ways, demonstrate the life-saving impacts of effective policies and prioritise interventions that are most likely to work.

This book is designed not to be a static textbook that is read once and accumulates dust.
It is meant to be a hand-book, taken out into the field of applied research and referred to frequently in the course of an analysis project.
As such, it is applied and exercise based.

There are strong links between data science, open data, open source software and more collaborative ways of working.
As such, this book is itself an open source, collaborative and open source project that is designed to be a living document.
We encourage any comments, questions or contributions related to its contents, the source code of which can be found at the Reproducible Road Safety Research with R ([rrsrr](https://github.com/saferactive/rrsrr)) repo on the [saferactive GitHub organisation](https://github.com/saferactive/), via the [issue tracker](https://github.com/saferactive/rrsrr/issues).
More broadly, we hope you enjoy the contents of the book and find the process of converting data science into data driven policy changes and investment rewarding.
Get ready for and enjoy the ride!

<!-- Comments/questions: should the stats19 package be introduced in a paper of its own right? -->

<!-- If you need PDF output, uncomment bookdown::pdf_book above in YAML. You will need a LaTeX installation, e.g., https://yihui.name/tinytex/ -->

<!-- ## Tests {-} -->

<!-- References that failed initially. -->

<!-- [@baath_state_2012] -->
